// <auto-generated />
namespace VinylCollector.Migrations.Vinyl
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class return_ArtistId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(return_ArtistId));
        
        string IMigrationMetadata.Id
        {
            get { return "201808202106288_return_ArtistId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
